### ISSUE TITLE
Cannot build with po4a 0.52 and 0.55

### ISSUE THREAD

**Issue by k-tamura** [openstandia/keycloak-documentation-i18n#1482]
I cannot build this project on elementary OS 0.4.1 Loki (Built on "Ubuntu 16.04.5 LTS") due to the following error:

```
asciidoctor: ERROR: topics/authorization-quickstarts.adoc: line 1263: table missing leading separator, recovering automatically
```

```bash
$ docker --version
Docker version 18.09.6, build 481bc77

$ mvn --version
Apache Maven 3.3.9
Maven home: /usr/share/maven
Java version: 9-internal, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-9-openjdk-amd64
Default locale: ja_JP, platform encoding: UTF-8
OS name: "linux", version: "4.15.0-42-generic", arch: "amd64", family: "unix"

$ po4a --version
po4a version 0.52.
written by Martin Quinson and Denis Barbier.

Copyright (C) 2002, 2003, 2004 Software in the Public Interest, Inc.
This is free software; see source code for copying
conditions. There is NO warranty; not even for
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by wadahiro** [comment]
To build successfully, we need to use po4a 0.52 patched version which is provided by [Docker Container on Docker Hub](https://hub.docker.com/r/openstandia/keycloak-documentation-i18n/tags) (The source code is [here](https://github.com/openstandia/keycloak-documentation-i18n/blob/po4a-patch/Dockerfile)).

Also, to use this container, you shouldn't install original po4a locally because current build script `build-translation.sh` [try to use it if it is installed](https://github.com/openstandia/keycloak-documentation-i18n/blob/master/build-translation.sh#L52-L57).

**Comment by wadahiro** [comment]
So I'll close pull request: #1483 because we don't need po4a locally.
